try{
    let a = 10/2;
    if(a==5){
        throw "invalid";
    }
}catch(err){
    console.log("yes");
}